%ifndef __icm32_INC__
%define __icm32_INC__

IMPORT CMCheckColors, 20
IMPORT CMCheckColorsInGamut, 16
IMPORT CMCheckRGBs, 36
IMPORT CMConvertColorNameToIndex, 16
IMPORT CMConvertIndexToColorName, 16
IMPORT CMCreateDeviceLinkProfile, 24
IMPORT CMCreateMultiProfileTransform, 20
IMPORT CMCreateProfile, 8
IMPORT CMCreateProfileW, 8
IMPORT CMCreateTransform, 12
IMPORT CMCreateTransformExt, 16
IMPORT CMCreateTransformExtW, 16
IMPORT CMCreateTransformW, 12
IMPORT CMDeleteTransform, 4
IMPORT CMGetInfo, 4
IMPORT CMGetNamedProfileInfo, 8
IMPORT CMIsProfileValid, 8
IMPORT CMTranslateColors, 24
IMPORT CMTranslateRGB, 16
IMPORT CMTranslateRGBs, 36
IMPORT CMTranslateRGBsExt, 44

%endif