%ifndef __msgina_INC__
%define __msgina_INC__

IMPORT WlxActivateUserShell, 16
IMPORT WlxDisplayLockedNotice, 4
IMPORT WlxDisplaySASNotice, 4
IMPORT WlxDisplayStatusMessage, 20
IMPORT WlxGetStatusMessage, 16
IMPORT WlxInitialize, 20
IMPORT WlxIsLockOk, 4
IMPORT WlxIsLogoffOk, 4
IMPORT WlxLoggedOnSAS, 12
IMPORT WlxLoggedOutSAS, 32
IMPORT WlxLogoff, 4
IMPORT WlxNegotiate, 8
IMPORT WlxNetworkProviderLoad, 8
IMPORT WlxRemoveStatusMessage, 4
IMPORT WlxScreenSaverNotify, 8
IMPORT WlxShutdown, 8
IMPORT WlxStartApplication, 16
IMPORT WlxWkstaLockedSAS, 8

%endif