%ifndef __rassapi_INC__
%define __rassapi_INC__

IMPORT RasAdminCompressPhoneNumber, 8
IMPORT RasAdminDLLInit, 12
IMPORT RasAdminFreeBuffer, 4
IMPORT RasAdminGetErrorString, 12
IMPORT RasAdminGetUserAccountServer, 12
IMPORT RasAdminGetUserParms, 8
IMPORT RasAdminPortClearStatistics, 8
IMPORT RasAdminPortDisconnect, 8
IMPORT RasAdminPortEnum, 12
IMPORT RasAdminPortGetInfo, 20
IMPORT RasAdminServerGetInfo, 8
IMPORT RasAdminSetUserParms, 12
IMPORT RasAdminUserGetInfo, 12
IMPORT RasAdminUserSetInfo, 12

%endif