// resource.h
// based on windows.inc

#define LANG_NEUTRAL                                      0x0
#define LANG_BULGARIAN                                    0x2
#define LANG_CHINESE                                      0x4
#define LANG_CROATIAN                                     0x1A
#define LANG_CZECH                                        0x5
#define LANG_DANISH                                       0x6
#define LANG_DUTCH                                        0x13
#define LANG_ENGLISH                                      0x9
#define LANG_FINNISH                                      0x0B
#define LANG_FRENCH                                       0x0C
#define LANG_GERMAN                                       0x7
#define LANG_GREEK                                        0x8
#define LANG_HUNGARIAN                                    0x0E
#define LANG_ICELANDIC                                    0x0F
#define LANG_ITALIAN                                      0x10
#define LANG_JAPANESE                                     0x11
#define LANG_KOREAN                                       0x12
#define LANG_NORWEGIAN                                    0x14
#define LANG_POLISH                                       0x15
#define LANG_PORTUGUESE                                   0x16
#define LANG_ROMANIAN                                     0x18
#define LANG_RUSSIAN                                      0x19
#define LANG_SLOVAK                                       0x1B
#define LANG_SLOVENIAN                                    0x24
#define LANG_SPANISH                                      0x0A
#define LANG_SWEDISH                                      0x1D
#define LANG_TURKISH                                      0x1F
#define SUBLANG_NEUTRAL                                   0x0
#define SUBLANG_DEFAULT                                   0x1
#define SUBLANG_SYS_DEFAULT                               0x2
#define SUBLANG_CHINESE_TRADITIONAL                       0x1
#define SUBLANG_CHINESE_SIMPLIFIED                        0x2
#define SUBLANG_CHINESE_HONGKONG                          0x3
#define SUBLANG_CHINESE_SINGAPORE                         0x4
#define SUBLANG_DUTCH                                     0x1
#define SUBLANG_DUTCH_BELGIAN                             0x2
#define SUBLANG_ENGLISH_US                                0x1
#define SUBLANG_ENGLISH_UK                                0x2
#define SUBLANG_ENGLISH_AUS                               0x3
#define SUBLANG_ENGLISH_CAN                               0x4
#define SUBLANG_ENGLISH_NZ                                0x5
#define SUBLANG_ENGLISH_EIRE                              0x6
#define SUBLANG_FRENCH                                    0x1
#define SUBLANG_FRENCH_BELGIAN                            0x2
#define SUBLANG_FRENCH_CANADIAN                           0x3
#define SUBLANG_FRENCH_SWISS                              0x4
#define SUBLANG_GERMAN                                    0x1
#define SUBLANG_GERMAN_SWISS                              0x2
#define SUBLANG_GERMAN_AUSTRIAN                           0x3
#define SUBLANG_ITALIAN                                   0x1
#define SUBLANG_ITALIAN_SWISS                             0x2
#define SUBLANG_NORWEGIAN_BOKMAL                          0x1
#define SUBLANG_NORWEGIAN_NYNORSK                         0x2
#define SUBLANG_PORTUGUESE                                0x2
#define SUBLANG_PORTUGUESE_BRAZILIAN                      0x1
#define SUBLANG_SPANISH                                   0x1
#define SUBLANG_SPANISH_MEXICAN                           0x2
#define SUBLANG_SPANISH_MODERN                            0x3
#define SORT_DEFAULT                                      0x0
#define SORT_JAPANESE_XJIS                                0x0
#define SORT_JAPANESE_UNICODE                             0x1
#define SORT_CHINESE_BIG5                                 0x0
#define SORT_CHINESE_UNICODE                              0x1
#define SORT_KOREAN_KSC                                   0x0
#define SORT_KOREAN_UNICODE                               0x1
#define RT_CURSOR                                         1
#define RT_BITMAP                                         2
#define RT_ICON                                           3
#define RT_MENU                                           4
#define RT_DIALOG                                         5
#define RT_STRING                                         6
#define RT_FONTDIR                                        7
#define RT_FONT                                           8
#define RT_ACCELERATOR                                    9
#define RT_RCDATA                                         10
#define SW_HIDE                                           0
#define SW_SHOWNORMAL                                     1
#define SW_NORMAL                                         1
#define SW_SHOWMINIMIZED                                  2
#define SW_SHOWMAXIMIZED                                  3
#define SW_MAXIMIZE                                       3
#define SW_SHOWNOACTIVATE                                 4
#define SW_SHOW                                           5
#define SW_MINIMIZE                                       6
#define SW_SHOWMINNOACTIVE                                7
#define SW_SHOWNA                                         8
#define SW_RESTORE                                        9
#define SW_SHOWDEFAULT                                    10
#define SW_MAX                                            10
#define HIDE_WINDOW                                       0
#define SHOW_OPENWINDOW                                   1
#define SHOW_ICONWINDOW                                   2
#define SHOW_FULLSCREEN                                   3
#define SHOW_OPENNOACTIVATE                               4
#define SW_PARENTCLOSING                                  1
#define SW_OTHERZOOM                                      2
#define SW_PARENTOPENING                                  3
#define SW_OTHERUNZOOM                                    4
#define VK_BACK                                           0x8
#define VK_CANCEL                                         0x3
#define VK_CAPITAL                                        0x14
#define VK_CLEAR                                          0x0C
#define VK_CONTROL                                        0x11
#define VK_DELETE                                         0x2E
#define VK_DOWN                                           0x28
#define VK_END                                            0x23
#define VK_ESCAPE                                         0x1B
#define VK_EXECUTE                                        0x2B
#define VK_HELP                                           0x2F
#define VK_HOME                                           0x24
#define VK_INSERT                                         0x2D
#define VK_LBUTTON                                        0x1
#define VK_LEFT                                           0x25
#define VK_MBUTTON                                        0x4
#define VK_MENU                                           0x12
#define VK_NEXT                                           0x22
#define VK_PAUSE                                          0x13
#define VK_PRINT                                          0x2A
#define VK_PRIOR                                          0x21
#define VK_RBUTTON                                        0x2
#define VK_RETURN                                         0x0D
#define VK_RIGHT                                          0x27
#define VK_SELECT                                         0x29
#define VK_SHIFT                                          0x10
#define VK_SNAPSHOT                                       0x2C
#define VK_SPACE                                          0x20
#define VK_TAB                                            0x9
#define VK_UP                                             0x26
#define VK_NUMPAD0                                        0x60
#define VK_NUMPAD1                                        0x61
#define VK_NUMPAD2                                        0x62
#define VK_NUMPAD3                                        0x63
#define VK_NUMPAD4                                        0x64
#define VK_NUMPAD5                                        0x65
#define VK_NUMPAD6                                        0x66
#define VK_NUMPAD7                                        0x67
#define VK_NUMPAD8                                        0x68
#define VK_NUMPAD9                                        0x69
#define VK_MULTIPLY                                       0x6A
#define VK_ADD                                            0x6B
#define VK_SEPARATOR                                      0x6C
#define VK_SUBTRACT                                       0x6D
#define VK_DECIMAL                                        0x6E
#define VK_DIVIDE                                         0x6F
#define VK_F1                                             0x70
#define VK_F2                                             0x71
#define VK_F3                                             0x72
#define VK_F4                                             0x73
#define VK_F5                                             0x74
#define VK_F6                                             0x75
#define VK_F7                                             0x76
#define VK_F8                                             0x77
#define VK_F9                                             0x78
#define VK_F10                                            0x79
#define VK_F11                                            0x7A
#define VK_F12                                            0x7B
#define VK_F13                                            0x7C
#define VK_F14                                            0x7D
#define VK_F15                                            0x7E
#define VK_F16                                            0x7F
#define VK_F17                                            0x80
#define VK_F18                                            0x81
#define VK_F19                                            0x82
#define VK_F20                                            0x83
#define VK_F21                                            0x84
#define VK_F22                                            0x85
#define VK_F23                                            0x86
#define VK_F24                                            0x87
#define VK_NUMLOCK                                        0x90
#define VK_SCROLL                                         0x91
#define VK_LSHIFT                                         0x0A0
#define VK_RSHIFT                                         0x0A1
#define VK_LCONTROL                                       0x0A2
#define VK_RCONTROL                                       0x0A3
#define VK_LMENU                                          0x0A4
#define VK_RMENU                                          0x0A5
#define VK_ATTN                                           0x0F6
#define VK_CRSEL                                          0x0F7
#define VK_EXSEL                                          0x0F8
#define VK_EREOF                                          0x0F9
#define VK_PLAY                                           0x0FA
#define VK_ZOOM                                           0x0FB
#define VK_NONAME                                         0x0FC
#define VK_PA1                                            0x0FD
#define VK_OEM_CLEAR                                      0x0FE
#define WM_USER                                           0x400
#define WM_NULL                                           0x0
#define WM_CREATE                                         0x1
#define WM_DESTROY                                        0x2
#define WM_MOVE                                           0x3
#define WM_SIZE                                           0x5
#define WM_ACTIVATE                                       0x6
#define WA_INACTIVE                                       0
#define WA_ACTIVE                                         1
#define WA_CLICKACTIVE                                    2
#define WM_SETFOCUS                                       0x7
#define WM_KILLFOCUS                                      0x08
#define WM_ENABLE                                         0x0A
#define WM_SETREDRAW                                      0x0B
#define WM_SETTEXT                                        0x0C
#define WM_GETTEXT                                        0x0D
#define WM_GETTEXTLENGTH                                  0x0E
#define WM_PAINT                                          0x0F
#define WM_CLOSE                                          0x10
#define WM_QUERYENDSESSION                                0x11
#define WM_QUIT                                           0x12
#define WM_QUERYOPEN                                      0x13
#define WM_ERASEBKGND                                     0x14
#define WM_SYSCOLORCHANGE                                 0x15
#define WM_ENDSESSION                                     0x16
#define WM_SHOWWINDOW                                     0x18
#define WM_WININICHANGE                                   0x1A
#define WM_DEVMODECHANGE                                  0x1B
#define WM_ACTIVATEAPP                                    0x1C
#define WM_FONTCHANGE                                     0x1D
#define WM_TIMECHANGE                                     0x1E
#define WM_CANCELMODE                                     0x1F
#define WM_SETCURSOR                                      0x20
#define WM_MOUSEACTIVATE                                  0x21
#define WM_CHILDACTIVATE                                  0x22
#define WM_QUEUESYNC                                      0x23
#define WM_GETMINMAXINFO                                  0x24
#define WM_PAINTICON                                      0x26
#define WM_ICONERASEBKGND                                 0x27
#define WM_NEXTDLGCTL                                     0x28
#define WM_SPOOLERSTATUS                                  0x2A
#define WM_DRAWITEM                                       0x2B
#define WM_MEASUREITEM                                    0x2C
#define WM_DELETEITEM                                     0x2D
#define WM_VKEYTOITEM                                     0x2E
#define WM_CHARTOITEM                                     0x2F
#define WM_SETFONT                                        0x30
#define WM_GETFONT                                        0x31
#define WM_SETHOTKEY                                      0x32
#define WM_GETHOTKEY                                      0x33
#define WM_QUERYDRAGICON                                  0x37
#define WM_COMPAREITEM                                    0x39
#define WM_COMPACTING                                     0x41
#define WM_COMMNOTIFY                                     0x44
#define WM_WINDOWPOSCHANGING                              0x46
#define WM_WINDOWPOSCHANGED                               0x47
#define WM_POWER                                          0x48
#define PWR_OK                                            1
#define PWR_FAIL                                          -1
#define PWR_SUSPENDREQUEST                                1
#define PWR_SUSPENDRESUME                                 2
#define PWR_CRITICALRESUME                                3
#define WM_COPYDATA                                       0x4A
#define WM_CANCELJOURNAL                                  0x4B
#define WM_NOTIFY                                         0x4E
#define WM_TCARD                                          0x52
#define WM_HELP                                           0x53
#define WM_USERCHANGED                                    0x54
#define WM_NOTIFYFORMAT                                   0x55
#define WM_CONTEXTMENU                                    0x7B
#define WM_STYLECHANGING                                  0x7C
#define WM_STYLECHANGED                                   0x7D
#define WM_DISPLAYCHANGE                                  0x7E
#define WM_GETICON                                        0x7F
#define WM_SETICON                                        0x80
#define WM_NCCREATE                                       0x81
#define WM_NCDESTROY                                      0x82
#define WM_NCCALCSIZE                                     0x83
#define WM_NCHITTEST                                      0x84
#define WM_NCPAINT                                        0x85
#define WM_NCACTIVATE                                     0x86
#define WM_GETDLGCODE                                     0x87
#define WM_NCMOUSEMOVE                                    0x0A0
#define WM_NCLBUTTONDOWN                                  0x0A1
#define WM_NCLBUTTONUP                                    0x0A2
#define WM_NCLBUTTONDBLCLK                                0x0A3
#define WM_NCRBUTTONDOWN                                  0x0A4
#define WM_NCRBUTTONUP                                    0x0A5
#define WM_NCRBUTTONDBLCLK                                0x0A6
#define WM_NCMBUTTONDOWN                                  0x0A7
#define WM_NCMBUTTONUP                                    0x0A8
#define WM_NCMBUTTONDBLCLK                                0x0A9
#define WM_KEYFIRST                                       0x100
#define WM_KEYDOWN                                        0x100
#define WM_KEYUP                                          0x101
#define WM_CHAR                                           0x102
#define WM_DEADCHAR                                       0x103
#define WM_SYSKEYDOWN                                     0x104
#define WM_SYSKEYUP                                       0x105
#define WM_SYSCHAR                                        0x106
#define WM_SYSDEADCHAR                                    0x107
#define WM_KEYLAST                                        0x108
#define WM_INITDIALOG                                     0x110
#define WM_COMMAND                                        0x111
#define WM_SYSCOMMAND                                     0x112
#define WM_TIMER                                          0x113
#define WM_HSCROLL                                        0x114
#define WM_VSCROLL                                        0x115
#define WM_INITMENU                                       0x116
#define WM_INITMENUPOPUP                                  0x117
#define WM_MENUSELECT                                     0x11F
#define WM_MENUCHAR                                       0x120
#define WM_ENTERIDLE                                      0x121
#define WM_CTLCOLORMSGBOX                                 0x132
#define WM_CTLCOLOREDIT                                   0x133
#define WM_CTLCOLORLISTBOX                                0x134
#define WM_CTLCOLORBTN                                    0x135
#define WM_CTLCOLORDLG                                    0x136
#define WM_CTLCOLORSCROLLBAR                              0x137
#define WM_CTLCOLORSTATIC                                 0x138
#define WM_MOUSEFIRST                                     0x200
#define WM_MOUSEMOVE                                      0x200
#define WM_LBUTTONDOWN                                    0x201
#define WM_LBUTTONUP                                      0x202
#define WM_LBUTTONDBLCLK                                  0x203
#define WM_RBUTTONDOWN                                    0x204
#define WM_RBUTTONUP                                      0x205
#define WM_RBUTTONDBLCLK                                  0x206
#define WM_MBUTTONDOWN                                    0x207
#define WM_MBUTTONUP                                      0x208
#define WM_MBUTTONDBLCLK                                  0x209
#define WM_MOUSELAST                                      0x209
#define WM_PARENTNOTIFY                                   0x210
#define WM_ENTERMENULOOP                                  0x211
#define WM_EXITMENULOOP                                   0x212
#define WM_MDICREATE                                      0x220
#define WM_MDIDESTROY                                     0x221
#define WM_MDIACTIVATE                                    0x222
#define WM_MDIRESTORE                                     0x223
#define WM_MDINEXT                                        0x224
#define WM_MDIMAXIMIZE                                    0x225
#define WM_MDITILE                                        0x226
#define WM_MDICASCADE                                     0x227
#define WM_MDIICONARRANGE                                 0x228
#define WM_MDIGETACTIVE                                   0x229
#define WM_MDISETMENU                                     0x230
#define WM_DROPFILES                                      0x233
#define WM_MDIREFRESHMENU                                 0x234
#define WM_CUT                                            0x300
#define WM_COPY                                           0x301
#define WM_PASTE                                          0x302
#define WM_CLEAR                                          0x303
#define WM_UNDO                                           0x304
#define WM_RENDERFORMAT                                   0x305
#define WM_RENDERALLFORMATS                               0x306
#define WM_DESTROYCLIPBOARD                               0x307
#define WM_DRAWCLIPBOARD                                  0x308
#define WM_PAINTCLIPBOARD                                 0x309
#define WM_VSCROLLCLIPBOARD                               0x30A
#define WM_SIZECLIPBOARD                                  0x30B
#define WM_ASKCBFORMATNAME                                0x30C
#define WM_CHANGECBCHAIN                                  0x30D
#define WM_HSCROLLCLIPBOARD                               0x30E
#define WM_QUERYNEWPALETTE                                0x30F
#define WM_PALETTEISCHANGING                              0x310
#define WM_PALETTECHANGED                                 0x311
#define WM_HOTKEY                                         0x312
#define WM_PRINTCLIENT                                    0x318
#define WM_PENWINFIRST                                    0x380
#define WM_PENWINLAST                                     0x38F
#define HTERROR                                           -2
#define HTTRANSPARENT                                     -1
#define HTNOWHERE                                         0
#define HTCLIENT                                          1
#define HTCAPTION                                         2
#define HTSYSMENU                                         3
#define HTGROWBOX                                         4
#define HTSIZE                                            HTGROWBOX
#define HTMENU                                            5
#define HTHSCROLL                                         6
#define HTVSCROLL                                         7
#define HTMINBUTTON                                       8
#define HTMAXBUTTON                                       9
#define HTLEFT                                            10
#define HTRIGHT                                           11
#define HTTOP                                             12
#define HTTOPLEFT                                         13
#define HTTOPRIGHT                                        14
#define HTBOTTOM                                          15
#define HTBOTTOMLEFT                                      16
#define HTBOTTOMRIGHT                                     17
#define HTBORDER                                          18
#define HTREDUCE                                          HTMINBUTTON
#define HTZOOM                                            HTMAXBUTTON
#define HTSIZEFIRST                                       HTLEFT
#define HTSIZELAST                                        HTBOTTOMRIGHT
#define SMTO_NORMAL                                       0x0
#define SMTO_BLOCK                                        0x1
#define SMTO_ABORTIFHUNG                                  0x2
#define MA_ACTIVATE                                       1
#define MA_ACTIVATEANDEAT                                 2
#define MA_NOACTIVATE                                     3
#define MA_NOACTIVATEANDEAT                               4
#define SIZE_RESTORED                                     0
#define SIZE_MINIMIZED                                    1
#define SIZE_MAXIMIZED                                    2
#define SIZE_MAXSHOW                                      3
#define SIZE_MAXHIDE                                      4
#define SIZENORMAL                                        SIZE_RESTORED
#define SIZEICONIC                                        SIZE_MINIMIZED
#define SIZEFULLSCREEN                                    SIZE_MAXIMIZED
#define SIZEZOOMSHOW                                      SIZE_MAXSHOW
#define SIZEZOOMHIDE                                      SIZE_MAXHIDE
#define WVR_ALIGNTOP                                      0x10
#define WVR_ALIGNLEFT                                     0x20
#define WVR_ALIGNBOTTOM                                   0x40
#define WVR_ALIGNRIGHT                                    0x80
#define WVR_HREDRAW                                       0x100
#define WVR_VREDRAW                                       0x200
#define WVR_REDRAW                                        (WVR_HREDRAW|WVR_VREDRAW)
#define WVR_VALIDRECTS                                    0x400
#define MK_LBUTTON                                        0x1
#define MK_RBUTTON                                        0x2
#define MK_SHIFT                                          0x4
#define MK_CONTROL                                        0x8
#define MK_MBUTTON                                        0x10
#define WS_OVERLAPPED                                     0x0
#define WS_POPUP                                          0x80000000
#define WS_CHILD                                          0x40000000
#define WS_MINIMIZE                                       0x20000000
#define WS_VISIBLE                                        0x10000000
#define WS_DISABLED                                       0x8000000
#define WS_CLIPSIBLINGS                                   0x4000000
#define WS_CLIPCHILDREN                                   0x2000000
#define WS_MAXIMIZE                                       0x1000000
#define WS_CAPTION                                        0x0C00000
#define WS_BORDER                                         0x800000
#define WS_DLGFRAME                                       0x400000
#define WS_VSCROLL                                        0x200000
#define WS_HSCROLL                                        0x100000
#define WS_SYSMENU                                        0x80000
#define WS_THICKFRAME                                     0x40000
#define WS_GROUP                                          0x20000
#define WS_TABSTOP                                        0x10000
#define WS_MINIMIZEBOX                                    0x20000
#define WS_MAXIMIZEBOX                                    0x10000
#define WS_TILED                                          WS_OVERLAPPED
#define WS_ICONIC                                         WS_MINIMIZE
#define WS_SIZEBOX                                        WS_THICKFRAME
#define WS_OVERLAPPEDWINDOW                               (WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_THICKFRAME|WS_MINIMIZEBOX|WS_MAXIMIZEBOX)
#define WS_TILEDWINDOW                                    WS_OVERLAPPEDWINDOW
#define WS_POPUPWINDOW                                    (WS_POPUP|WS_BORDER|WS_SYSMENU)
#define WS_CHILDWINDOW                                    WS_CHILD
#define WS_EX_DLGMODALFRAME                               0x1
#define WS_EX_NOPARENTNOTIFY                              0x4
#define WS_EX_TOPMOST                                     0x8
#define WS_EX_ACCEPTFILES                                 0x10
#define WS_EX_TRANSPARENT                                 0x20
#define WS_EX_MDICHILD                                    0x00000040
#define WS_EX_TOOLWINDOW                                  0x00000080
#define WS_EX_WINDOWEDGE                                  0x00000100
#define WS_EX_CLIENTEDGE                                  0x00000200
#define WS_EX_CONTEXTHELP                                 0x00000400
#define WS_EX_RIGHT                                       0x00001000
#define WS_EX_LEFT                                        0x00000000
#define WS_EX_RTLREADING                                  0x00002000
#define WS_EX_LTRREADING                                  0x00000000
#define WS_EX_LEFTSCROLLBAR                               0x00004000
#define WS_EX_RIGHTSCROLLBAR                              0x00000000
#define WS_EX_CONTROLPARENT                               0x00010000
#define WS_EX_STATICEDGE                                  0x00020000
#define WS_EX_APPWINDOW                                   0x00040000
#define WS_EX_OVERLAPPEDWINDOW                            (WS_EX_WINDOWEDGE|WS_EX_CLIENTEDGE)
#define WS_EX_PALETTEWINDOW                               (WS_EX_WINDOWEDGE|WS_EX_TOOLWINDOW|WS_EX_TOPMOST)
#define CS_VREDRAW                                        0x1
#define CS_HREDRAW                                        0x2
#define CS_DBLCLKS                                        0x8
#define CS_OWNDC                                          0x20
#define CS_CLASSDC                                        0x40
#define CS_PARENTDC                                       0x80
#define CS_NOCLOSE                                        0x200
#define CS_SAVEBITS                                       0x800
#define CS_BYTEALIGNCLIENT                                0x1000
#define CS_BYTEALIGNWINDOW                                0x2000
#define CS_GLOBALCLASS                                    CS_PUBLICCLASS
#define CF_TEXT                                           1
#define CF_BITMAP                                         2
#define CF_METAFILEPICT                                   3
#define CF_SYLK                                           4
#define CF_DIF                                            5
#define CF_TIFF                                           6
#define CF_OEMTEXT                                        7
#define CF_DIB                                            8
#define CF_PALETTE                                        9
#define CF_PENDATA                                        10
#define CF_RIFF                                           11
#define CF_WAVE                                           12
#define CF_OWNERDISPLAY                                   0x80
#define CF_DSPTEXT                                        0x81
#define CF_DSPBITMAP                                      0x82
#define CF_DSPMETAFILEPICT                                0x83
#define CF_DSPENHMETAFILE                                 0x8E
#define CF_PRIVATEFIRST                                   0x200
#define CF_PRIVATELAST                                    0x2FF
#define CF_GDIOBJFIRST                                    0x300
#define CF_GDIOBJLAST                                     0x3FF
#define MF_INSERT                                         0x0
#define MF_CHANGE                                         0x80
#define MF_APPEND                                         0x100
#define MF_DELETE                                         0x200
#define MF_REMOVE                                         0x1000
#define MF_BYCOMMAND                                      0x0
#define MF_BYPOSITION                                     0x400
#define MF_SEPARATOR                                      0x800
#define MF_ENABLED                                        0x0
#define MF_GRAYED                                         0x1
#define MF_DISABLED                                       0x2
#define MF_UNCHECKED                                      0x0
#define MF_CHECKED                                        0x8
#define MF_USECHECKBITMAPS                                0x200
#define MF_STRING                                         0x0
#define MF_BITMAP                                         0x4
#define MF_OWNERDRAW                                      0x100
#define MF_POPUP                                          0x10
#define MF_MENUBARBREAK                                   0x20
#define MF_MENUBREAK                                      0x40
#define MF_UNHILITE                                       0x0
#define MF_HILITE                                         0x80
#define MF_SYSMENU                                        0x2000
#define MF_HELP                                           0x4000
#define MF_MOUSESELECT                                    0x8000
#define MF_END                                            0x80
#define SC_SIZE                                           0x0F000
#define SC_MOVE                                           0x0F010
#define SC_MINIMIZE                                       0x0F020
#define SC_MAXIMIZE                                       0x0F030
#define SC_NEXTWINDOW                                     0x0F040
#define SC_PREVWINDOW                                     0x0F050
#define SC_CLOSE                                          0x0F060
#define SC_VSCROLL                                        0x0F070
#define SC_HSCROLL                                        0x0F080
#define SC_MOUSEMENU                                      0x0F090
#define SC_KEYMENU                                        0x0F100
#define SC_ARRANGE                                        0x0F110
#define SC_RESTORE                                        0x0F120
#define SC_TASKLIST                                       0x0F130
#define SC_SCREENSAVE                                     0x0F140
#define SC_HOTKEY                                         0x0F150
#define SC_ICON                                           SC_MINIMIZE
#define SC_ZOOM                                           SC_MAXIMIZE
#define OBM_CLOSE                                         32754
#define OBM_UPARROW                                       32753
#define OBM_DNARROW                                       32752
#define OBM_RGARROW                                       32751
#define OBM_LFARROW                                       32750
#define OBM_REDUCE                                        32749
#define OBM_ZOOM                                          32748
#define OBM_RESTORE                                       32747
#define OBM_REDUCED                                       32746
#define OBM_ZOOMD                                         32745
#define OBM_RESTORED                                      32744
#define OBM_UPARROWD                                      32743
#define OBM_DNARROWD                                      32742
#define OBM_RGARROWD                                      32741
#define OBM_LFARROWD                                      32740
#define OBM_MNARROW                                       32739
#define OBM_COMBO                                         32738
#define OBM_UPARROWI                                      32737
#define OBM_DNARROWI                                      32736
#define OBM_RGARROWI                                      32735
#define OBM_LFARROWI                                      32734
#define OBM_OLD_CLOSE                                     32767
#define OBM_SIZE                                          32766
#define OBM_OLD_UPARROW                                   32765
#define OBM_OLD_DNARROW                                   32764
#define OBM_OLD_RGARROW                                   32763
#define OBM_OLD_LFARROW                                   32762
#define OBM_BTSIZE                                        32761
#define OBM_CHECK                                         32760
#define OBM_CHECKBOXES                                    32759
#define OBM_BTNCORNERS                                    32758
#define OBM_OLD_REDUCE                                    32757
#define OBM_OLD_ZOOM                                      32756
#define OBM_OLD_RESTORE                                   32755
#define OCR_NORMAL                                        32512
#define OCR_IBEAM                                         32513
#define OCR_WAIT                                          32514
#define OCR_CROSS                                         32515
#define OCR_UP                                            32516
#define OCR_SIZE                                          32640
#define OCR_ICON                                          32641
#define OCR_SIZENWSE                                      32642
#define OCR_SIZENESW                                      32643
#define OCR_SIZEWE                                        32644
#define OCR_SIZENS                                        32645
#define OCR_SIZEALL                                       32646
#define OCR_ICOCUR                                        32647
#define OCR_NO                                            32648
#define OIC_SAMPLE                                        32512
#define OIC_HAND                                          32513
#define OIC_QUES                                          32514
#define OIC_BANG                                          32515
#define OIC_NOTE                                          32516
#define IDI_APPLICATION                                   32512
#define IDI_HAND                                          32513
#define IDI_QUESTION                                      32514
#define IDI_EXCLAMATION                                   32515
#define IDI_ASTERISK                                      32516
#define IDOK                                              1
#define IDCANCEL                                          2
#define IDABORT                                           3
#define IDRETRY                                           4
#define IDIGNORE                                          5
#define IDYES                                             6
#define IDNO                                              7
#define ES_LEFT                                           0x0
#define ES_CENTER                                         0x1
#define ES_RIGHT                                          0x2
#define ES_MULTILINE                                      0x4
#define ES_UPPERCASE                                      0x8
#define ES_LOWERCASE                                      0x10
#define ES_PASSWORD                                       0x20
#define ES_AUTOVSCROLL                                    0x40
#define ES_AUTOHSCROLL                                    0x80
#define ES_NOHIDESEL                                      0x100
#define ES_OEMCONVERT                                     0x400
#define ES_READONLY                                       0x800
#define ES_WANTRETURN                                     0x1000
#define EM_GETSEL                                         0x0B0
#define EM_SETSEL                                         0x0B1
#define EM_GETRECT                                        0x0B2
#define EM_SETRECT                                        0x0B3
#define EM_SETRECTNP                                      0x0B4
#define EM_SCROLL                                         0x0B5
#define EM_LINESCROLL                                     0x0B6
#define EM_SCROLLCARET                                    0x0B7
#define EM_GETMODIFY                                      0x0B8
#define EM_SETMODIFY                                      0x0B9
#define EM_GETLINECOUNT                                   0x0BA
#define EM_LINEINDEX                                      0x0BB
#define EM_SETHANDLE                                      0x0BC
#define EM_GETHANDLE                                      0x0BD
#define EM_GETTHUMB                                       0x0BE
#define EM_LINELENGTH                                     0x0C1
#define EM_REPLACESEL                                     0x0C2
#define EM_GETLINE                                        0x0C4
#define EM_LIMITTEXT                                      0x0C5
#define EM_CANUNDO                                        0x0C6
#define EM_UNDO                                           0x0C7
#define EM_FMTLINES                                       0x0C8
#define EM_LINEFROMCHAR                                   0x0C9
#define EM_SETTABSTOPS                                    0x0CB
#define EM_SETPASSWORDCHAR                                0x0CC
#define EM_EMPTYUNDOBUFFER                                0x0CD
#define EM_GETFIRSTVISIBLELINE                            0x0CE
#define EM_SETREADONLY                                    0x0CF
#define EM_SETWORDBREAKPROC                               0x0D0
#define EM_GETWORDBREAKPROC                               0x0D1
#define EM_GETPASSWORDCHAR                                0x0D2
#define EM_SETMARGINS                                     0x0D3
#define EM_GETMARGINS                                     0x0D4
#define EM_SETLIMITTEXT                                   EM_LIMITTEXT
#define EM_GETLIMITTEXT                                   0x0D5
#define EM_POSFROMCHAR                                    0x0D6
#define EM_CHARFROMPOS                                    0x0D7
#define BS_PUSHBUTTON                                     0x0
#define BS_DEFPUSHBUTTON                                  0x1
#define BS_CHECKBOX                                       0x2
#define BS_AUTOCHECKBOX                                   0x3
#define BS_RADIOBUTTON                                    0x4
#define BS_3STATE                                         0x5
#define BS_AUTO3STATE                                     0x6
#define BS_GROUPBOX                                       0x7
#define BS_USERBUTTON                                     0x8
#define BS_AUTORADIOBUTTON                                0x9
#define BS_OWNERDRAW                                      0x0B
#define BS_LEFTTEXT                                       0x20
#define BS_BITMAP                                         0x80
#define BS_ICON                                           0x40
#define BN_CLICKED                                        0
#define BN_PAINT                                          1
#define BN_HILITE                                         2
#define BN_UNHILITE                                       3
#define BN_DISABLE                                        4
#define BN_DOUBLECLICKED                                  5
#define BN_SETFOCUS                                       6
#define BN_KILLFOCUS                                      7
#define BST_UNCHECKED                                     0x00
#define BST_CHECKED                                       0x01
#define BST_INDETERMINATE                                 0x02
#define BST_PUSHED                                        0x04
#define BM_GETCHECK                                       0x0F0
#define BM_SETCHECK                                       0x0F1
#define BM_GETSTATE                                       0x0F2
#define BM_SETSTATE                                       0x0F3
#define BM_SETSTYLE                                       0x0F4
#define BM_CLICK                                          0x0F5
#define BM_GETIMAGE                                       0x0F6
#define BM_SETIMAGE                                       0x0F7
#define SS_LEFT                                           0x0
#define SS_CENTER                                         0x1
#define SS_RIGHT                                          0x2
#define SS_ICON                                           0x3
#define SS_BLACKRECT                                      0x4
#define SS_GRAYRECT                                       0x5
#define SS_WHITERECT                                      0x6
#define SS_BLACKFRAME                                     0x7
#define SS_GRAYFRAME                                      0x8
#define SS_WHITEFRAME                                     0x9
#define SS_USERITEM                                       0x0A
#define SS_SIMPLE                                         0x0B
#define SS_LEFTNOWORDWRAP                                 0x0C
#define SS_NOPREFIX                                       0x80
#define DS_ABSALIGN                                       0x0001
#define DS_SYSMODAL                                       0x0002
#define DS_3DLOOK                                         0x0004
#define DS_FIXEDSYS                                       0x0008
#define DS_NOFAILCREATE                                   0x0010
#define DS_LOCALEDIT                                      0x0020
#define DS_SETFONT                                        0x0040
#define DS_MODALFRAME                                     0x0080
#define DS_NOIDLEMSG                                      0x0100
#define DS_SETFOREGROUND                                  0x0200
#define DS_CONTROL                                        0x0400
#define DS_CENTER                                         0x0800
#define DS_CENTERMOUSE                                    0x1000
#define DS_CONTEXTHELP                                    0x2000
#define LBS_NOTIFY                                        0x1
#define LBS_SORT                                          0x2
#define LBS_NOREDRAW                                      0x4
#define LBS_MULTIPLESEL                                   0x8
#define LBS_OWNERDRAWFIXED                                0x10
#define LBS_OWNERDRAWVARIABLE                             0x20
#define LBS_HASSTRINGS                                    0x40
#define LBS_USETABSTOPS                                   0x80
#define LBS_NOINTEGRALHEIGHT                              0x100
#define LBS_MULTICOLUMN                                   0x200
#define LBS_WANTKEYBOARDINPUT                             0x400
#define LBS_EXTENDEDSEL                                   0x800
#define LBS_DISABLENOSCROLL                               0x1000
#define LBS_NODATA                                        0x2000
#define LBS_STANDARD                                      (LBS_NOTIFY|LBS_SORT|WS_VSCROLL|WS_BORDER)
#define CBS_SIMPLE                                        0x1
#define CBS_DROPDOWN                                      0x2
#define CBS_DROPDOWNLIST                                  0x3
#define CBS_OWNERDRAWFIXED                                0x10
#define CBS_OWNERDRAWVARIABLE                             0x20
#define CBS_AUTOHSCROLL                                   0x40
#define CBS_OEMCONVERT                                    0x80
#define CBS_SORT                                          0x100
#define CBS_HASSTRINGS                                    0x200
#define CBS_NOINTEGRALHEIGHT                              0x400
#define CBS_DISABLENOSCROLL                               0x800
#define SBS_HORZ                                          0x0
#define SBS_VERT                                          0x1
#define SBS_TOPALIGN                                      0x2
#define SBS_LEFTALIGN                                     0x2
#define SBS_BOTTOMALIGN                                   0x4
#define SBS_RIGHTALIGN                                    0x4
#define SBS_SIZEBOXTOPLEFTALIGN                           0x2
#define SBS_SIZEBOXBOTTOMRIGHTALIGN                       0x4
#define SBS_SIZEBOX                                       0x8
#define SBS_SIZEGRIP                                      0x10
#define HELP_CONTEXT                                      0x1
#define HELP_QUIT                                         0x2
#define HELP_INDEX                                        0x3
#define HELP_CONTENTS                                     0x3
#define HELP_HELPONHELP                                   0x4
#define HELP_SETINDEX                                     0x5
#define HELP_SETCONTENTS                                  0x5
#define HELP_CONTEXTPOPUP                                 0x8
#define HELP_FORCEFILE                                    0x9
#define HELP_KEY                                          0x101
#define HELP_COMMAND                                      0x102
#define HELP_PARTIALKEY                                   0x105
#define HELP_MULTIKEY                                     0x201
#define HELP_SETWINPOS                                    0x203
#define HELP_CONTEXTMENU                                  0x000A
#define HELP_FINDER                                       0x000B
#define HELP_WM_HELP                                      0x000C
#define HELP_SETPOPUP_POS                                 0x000D
#define HELP_TCARD                                        0x8000
#define HELP_TCARD_DATA                                   0x0010
#define HELP_TCARD_OTHER_CALLER                           0x0011
#define IDH_NO_HELP                                       28440
#define IDH_MISSING_CONTEXT                               28441
#define IDH_GENERIC_HELP_BUTTON                           28442
#define IDH_OK                                            28443
#define IDH_CANCEL                                        28444
#define IDH_HELP                                          28445
#define WM_DDE_FIRST                                      0x3E0
#define WM_DDE_INITIATE                                   WM_DDE_FIRST
#define WM_DDE_TERMINATE                                  (WM_DDE_FIRST+1)
#define WM_DDE_ADVISE                                     (WM_DDE_FIRST+2)
#define WM_DDE_UNADVISE                                   (WM_DDE_FIRST+3)
#define WM_DDE_ACK                                        (WM_DDE_FIRST+4)
#define WM_DDE_DATA                                       (WM_DDE_FIRST+5)
#define WM_DDE_REQUEST                                    (WM_DDE_FIRST+6)
#define WM_DDE_POKE                                       (WM_DDE_FIRST+7)
#define WM_DDE_EXECUTE                                    (WM_DDE_FIRST+8)
#define WM_DDE_LAST                                       (WM_DDE_FIRST+8)
#define ctlFirst                                          0x400
#define ctlLast                                           0x4FF
#define psh1                                              0x400
#define psh2                                              0x401
#define psh3                                              0x402
#define psh4                                              0x403
#define psh5                                              0x404
#define psh6                                              0x405
#define psh7                                              0x406
#define psh8                                              0x407
#define psh9                                              0x408
#define psh10                                             0x409
#define psh11                                             0x40A
#define psh12                                             0x40B
#define psh13                                             0x40C
#define psh14                                             0x40D
#define psh15                                             0x40E
#define pshHelp                                           psh15
#define psh16                                             0x40F
#define chx1                                              0x410
#define chx2                                              0x411
#define chx3                                              0x412
#define chx4                                              0x413
#define chx5                                              0x414
#define chx6                                              0x415
#define chx7                                              0x416
#define chx8                                              0x417
#define chx9                                              0x418
#define chx10                                             0x419
#define chx11                                             0x41A
#define chx12                                             0x41B
#define chx13                                             0x41C
#define chx14                                             0x41D
#define chx15                                             0x41E
#define chx16                                             0x41D
#define rad1                                              0x420
#define rad2                                              0x421
#define rad3                                              0x422
#define rad4                                              0x423
#define rad5                                              0x424
#define rad6                                              0x425
#define rad7                                              0x426
#define rad8                                              0x427
#define rad9                                              0x428
#define rad10                                             0x429
#define rad11                                             0x42A
#define rad12                                             0x42B
#define rad13                                             0x42C
#define rad14                                             0x42D
#define rad15                                             0x42E
#define rad16                                             0x42F
#define grp1                                              0x430
#define grp2                                              0x431
#define grp3                                              0x432
#define grp4                                              0x433
#define frm1                                              0x434
#define frm2                                              0x435
#define frm3                                              0x436
#define frm4                                              0x437
#define rct1                                              0x438
#define rct2                                              0x439
#define rct3                                              0x43A
#define rct4                                              0x43B
#define ico1                                              0x43C
#define ico2                                              0x43D
#define ico3                                              0x43E
#define ico4                                              0x43F
#define stc1                                              0x440
#define stc2                                              0x441
#define stc3                                              0x442
#define stc4                                              0x443
#define stc5                                              0x444
#define stc6                                              0x445
#define stc7                                              0x446
#define stc8                                              0x447
#define stc9                                              0x448
#define stc10                                             0x449
#define stc11                                             0x44A
#define stc12                                             0x44B
#define stc13                                             0x44C
#define stc14                                             0x44D
#define stc15                                             0x44E
#define stc16                                             0x44F
#define stc17                                             0x450
#define stc18                                             0x451
#define stc19                                             0x452
#define stc20                                             0x453
#define stc21                                             0x454
#define stc22                                             0x455
#define stc23                                             0x456
#define stc24                                             0x457
#define stc25                                             0x458
#define stc26                                             0x459
#define stc27                                             0x45A
#define stc28                                             0x45B
#define stc29                                             0x45C
#define stc30                                             0x45D
#define stc31                                             0x45E
#define stc32                                             0x45F
#define lst1                                              0x460
#define lst2                                              0x461
#define lst3                                              0x462
#define lst4                                              0x463
#define lst5                                              0x464
#define lst6                                              0x465
#define lst7                                              0x466
#define lst8                                              0x467
#define lst9                                              0x468
#define lst10                                             0x469
#define lst11                                             0x46A
#define lst12                                             0x46B
#define lst13                                             0x46C
#define lst14                                             0x46D
#define lst15                                             0x46E
#define lst16                                             0x46F
#define cmb1                                              0x470
#define cmb2                                              0x471
#define cmb3                                              0x472
#define cmb4                                              0x473
#define cmb5                                              0x474
#define cmb6                                              0x475
#define cmb7                                              0x476
#define cmb8                                              0x477
#define cmb9                                              0x478
#define cmb10                                             0x479
#define cmb11                                             0x47A
#define cmb12                                             0x47B
#define cmb13                                             0x47C
#define cmb14                                             0x47D
#define cmb15                                             0x47E
#define cmb16                                             0x47F
#define edt1                                              0x480
#define edt2                                              0x481
#define edt3                                              0x482
#define edt4                                              0x483
#define edt5                                              0x484
#define edt6                                              0x485
#define edt7                                              0x486
#define edt8                                              0x487
#define edt9                                              0x488
#define edt10                                             0x489
#define edt11                                             0x48A
#define edt12                                             0x48B
#define edt13                                             0x48C
#define edt14                                             0x48D
#define edt15                                             0x48E
#define edt16                                             0x48F
#define scr1                                              0x490
#define scr2                                              0x491
#define scr3                                              0x492
#define scr4                                              0x493
#define scr5                                              0x494
#define scr6                                              0x495
#define scr7                                              0x496
#define scr8                                              0x497
#define FILEOPENORD                                       1536
#define MULTIFILEOPENORD                                  1537
#define PRINTDLGORD                                       1538
#define PRNSETUPDLGORD                                    1539
#define FINDDLGORD                                        1540
#define REPLACEDLGORD                                     1541
#define FONTDLGORD                                        1542
#define FORMATDLGORD31                                    1543
#define FORMATDLGORD30                                    1544
#define VK_PROCESSKEY                                     0x0E5
#define WM_IME_STARTCOMPOSITION                           0x10D
#define WM_IME_ENDCOMPOSITION                             0x10E
#define WM_IME_COMPOSITION                                0x10F
#define WM_IME_KEYLAST                                    0x10F
#define WM_IME_SETCONTEXT                                 0x281
#define WM_IME_NOTIFY                                     0x282
#define WM_IME_CONTROL                                    0x283
#define WM_IME_COMPOSITIONFULL                            0x284
#define WM_IME_SELECT                                     0x285
#define WM_IME_CHAR                                       0x286
#define WM_IME_KEYDOWN                                    0x290
#define WM_IME_KEYUP                                      0x291
#define VS_VERSION_INFO                                   1
#define VS_USER_DEFINED                                   100
#define VS_FFI_SIGNATURE                                  0x0FEEF04BD
#define VS_FFI_STRUCVERSION                               0x10000
#define VS_FFI_FILEFLAGSMASK                              0x3F
#define VS_FF_DEBUG                                       0x1
#define VS_FF_PRERELEASE                                  0x2
#define VS_FF_PATCHED                                     0x4
#define VS_FF_PRIVATEBUILD                                0x8
#define VS_FF_INFOINFERRED                                0x10
#define VS_FF_SPECIALBUILD                                0x20
#define VOS_UNKNOWN                                       0x0
#define VOS_DOS                                           0x10000
#define VOS_OS216                                         0x20000
#define VOS_OS232                                         0x30000
#define VOS_NT                                            0x40000
#define VOS__BASE                                         0x0
#define VOS__WINDOWS16                                    0x1
#define VOS__PM16                                         0x2
#define VOS__PM32                                         0x3
#define VOS__WINDOWS32                                    0x4
#define VOS_DOS_WINDOWS16                                 0x10001
#define VOS_DOS_WINDOWS32                                 0x10004
#define VOS_OS216_PM16                                    0x20002
#define VOS_OS232_PM32                                    0x30003
#define VOS_NT_WINDOWS32                                  0x40004
#define VFT_UNKNOWN                                       0x0
#define VFT_APP                                           0x1
#define VFT_DLL                                           0x2
#define VFT_DRV                                           0x3
#define VFT_FONT                                          0x4
#define VFT_VXD                                           0x5
#define VFT_STATIC_LIB                                    0x7
#define VFT2_UNKNOWN                                      0x0
#define VFT2_DRV_PRINTER                                  0x1
#define VFT2_DRV_KEYBOARD                                 0x2
#define VFT2_DRV_LANGUAGE                                 0x3
#define VFT2_DRV_DISPLAY                                  0x4
#define VFT2_DRV_MOUSE                                    0x5
#define VFT2_DRV_NETWORK                                  0x6
#define VFT2_DRV_SYSTEM                                   0x7
#define VFT2_DRV_INSTALLABLE                              0x8
#define VFT2_DRV_SOUND                                    0x9
#define VFT2_DRV_COMM                                     0x0A
#define VFT2_DRV_INPUTMETHOD                              0x0B
#define VFT2_FONT_RASTER                                  0x1
#define VFT2_FONT_VECTOR                                  0x2
#define VFT2_FONT_TRUETYPE                                0x3
#define VFFF_ISSHAREDFILE                                 0x1
#define VFF_CURNEDEST                                     0x1
#define VFF_FILEINUSE                                     0x2
#define VFF_BUFFTOOSMALL                                  0x4
#define VIFF_FORCEINSTALL                                 0x1
#define VIFF_DONTDELETEOLD                                0x2
#define VIF_TEMPFILE                                      0x1
#define VIF_MISMATCH                                      0x2
#define VIF_SRCOLD                                        0x4
#define VIF_DIFFLANG                                      0x8
#define VIF_DIFFCODEPG                                    0x10
#define VIF_DIFFTYPE                                      0x20
#define VIF_WRITEPROT                                     0x40
#define VIF_FILEINUSE                                     0x80
#define VIF_OUTOFSPACE                                    0x100
#define VIF_ACCESSVIOLATION                               0x200
#define VIF_SHARINGVIOLATION                              0x400
#define VIF_CANNOTCREATE                                  0x800
#define VIF_CANNOTDELETE                                  0x1000
#define VIF_CANNOTRENAME                                  0x2000
#define VIF_CANNOTDELETECUR                               0x4000
#define VIF_OUTOFMEMORY                                   0x8000
#define VIF_CANNOTREADSRC                                 0x10000
#define VIF_CANNOTREADDST                                 0x20000
#define VIF_BUFFTOOSMALL                                  0x40000
#define CCS_TOP                                           0x00000001
#define CCS_NOMOVEY                                       0x00000002
#define CCS_BOTTOM                                        0x00000003
#define CCS_NORESIZE                                      0x00000004
#define CCS_NOPARENTALIGN                                 0x00000008
#define CCS_ADJUSTABLE                                    0x00000020
#define CCS_NODIVIDER                                     0x00000040
#define RBS_TOOLTIPS                                      0x0100
#define RBS_VARHEIGHT                                     0x0200
#define RBS_BANDBORDERS                                   0x0400
#define RBS_FIXEDORDER                                    0x0800
#define RBS_REGISTERDROP                                  0x1000
#define RBS_AUTOSIZE                                      0x2000
#define RBS_VERTICALGRIPPER                               0x4000
#define RBS_DBLCLKTOGGLE                                  0x8000
#define HDS_HORZ                                          0x00000000
#define HDS_BUTTONS                                       0x00000002
#define HDS_HIDDEN                                        0x00000008
#define TTS_ALWAYSTIP                                     0x01
#define TTS_NOPREFIX                                      0x02
#define SBARS_SIZEGRIP                                    0x0100
#define TBS_AUTOTICKS                                     0x0001
#define TBS_VERT                                          0x0002
#define TBS_HORZ                                          0x0000
#define TBS_TOP                                           0x0004
#define TBS_BOTTOM                                        0x0000
#define TBS_LEFT                                          0x0004
#define TBS_RIGHT                                         0x0000
#define TBS_BOTH                                          0x0008
#define TBS_NOTICKS                                       0x0010
#define TBS_ENABLESELRANGE                                0x0020
#define TBS_FIXEDLENGTH                                   0x0040
#define TBS_NOTHUMB                                       0x0080
#define UDS_WRAP                                          0x0001
#define UDS_SETBUDDYINT                                   0x0002
#define UDS_ALIGNRIGHT                                    0x0004
#define UDS_ALIGNLEFT                                     0x0008
#define UDS_AUTOBUDDY                                     0x0010
#define UDS_ARROWKEYS                                     0x0020
#define UDS_HORZ                                          0x0040
#define UDS_NOTHOUSANDS                                   0x0080
#define LVS_ICON                                          0x0000
#define LVS_REPORT                                        0x0001
#define LVS_SMALLICON                                     0x0002
#define LVS_LIST                                          0x0003
#define LVS_TYPEMASK                                      0x0003
#define LVS_SINGLESEL                                     0x0004
#define LVS_SHOWSELALWAYS                                 0x0008
#define LVS_SORTASCENDING                                 0x0010
#define LVS_SORTDESCENDING                                0x0020
#define LVS_SHAREIMAGELISTS                               0x0040
#define LVS_NOLABELWRAP                                   0x0080
#define LVS_AUTOARRANGE                                   0x0100
#define LVS_EDITLABELS                                    0x0200
#define LVS_NOSCROLL                                      0x2000
#define LVS_TYPESTYLEMASK                                 0fc0x00
#define LVS_ALIGNTOP                                      0x0000
#define LVS_ALIGNLEFT                                     0x0800
#define LVS_ALIGNMASK                                     0c0x00
#define LVS_OWNERDRAWFIXED                                0x0400
#define LVS_NOCOLUMNHEADER                                0x4000
#define LVS_NOSORTHEADER                                  0x8000
#define TVS_HASBUTTONS                                    0x0001
#define TVS_HASLINES                                      0x0002
#define TVS_LINESATROOT                                   0x0004
#define TVS_EDITLABELS                                    0x0008
#define TVS_DISABLEDRAGDROP                               0x0010
#define TVS_SHOWSELALWAYS                                 0x0020
#define TCS_FORCEICONLEFT                                 0x0010
#define TCS_FORCELABELLEFT                                0x0020
#define TCS_TABS                                          0x0000
#define TCS_BUTTONS                                       0x0100
#define TCS_SINGLELINE                                    0x0000
#define TCS_MULTILINE                                     0x0200
#define TCS_RIGHTJUSTIFY                                  0x0000
#define TCS_FIXEDWIDTH                                    0x0400
#define TCS_RAGGEDRIGHT                                   0x0800
#define TCS_FOCUSONBUTTONDOWN                             0x1000
#define TCS_OWNERDRAWFIXED                                0x2000
#define TCS_TOOLTIPS                                      0x4000
#define TCS_FOCUSNEVER                                    0x8000
#define ACS_CENTER                                        0x0001
#define ACS_TRANSPARENT                                   0x0002
#define ACS_AUTOPLAY                                      0x0004
