%ifndef __activeds_INC__
%define __activeds_INC__

IMPORT ADsBuildEnumerator, 8
IMPORT ADsBuildVarArrayInt, 12
IMPORT ADsBuildVarArrayStr, 12
IMPORT ADsDecodeBinaryData, 12
IMPORT ADsEncodeBinaryData, 12
IMPORT ADsEnumerateNext, 16
IMPORT ADsFreeEnumerator, 4
IMPORT ADsGetLastError, 20
IMPORT ADsGetObject, 12
IMPORT ADsOpenObject, 24
IMPORT ADsSetLastError, 12
IMPORT AdsFreeAdsValues, 8
IMPORT AdsTypeToPropVariant2, 24
IMPORT AdsTypeToPropVariant, 12
IMPORT AllocADsMem, 4
IMPORT AllocADsStr, 4
IMPORT BinarySDToSecurityDescriptor, 24
IMPORT ConvertSecDescriptorToVariant, 20
IMPORT ConvertSecurityDescriptorToSecDes, 24
IMPORT ConvertTrusteeToSid, 24
IMPORT FreeADsMem, 4
IMPORT FreeADsStr, 4
IMPORT PropVariantToAdsType2, 28
IMPORT PropVariantToAdsType, 16
IMPORT ReallocADsMem, 12
IMPORT ReallocADsStr, 8
IMPORT SecurityDescriptorToBinarySD, 40

%endif