%ifndef __cryptui_INC__
%define __cryptui_INC__

IMPORT ACUIProviderInvokeUI, 4
IMPORT CryptUIDlgCertMgr, 4
IMPORT CryptUIDlgFreeCAContext, 4
IMPORT CryptUIDlgSelectCA, 4
IMPORT CryptUIDlgSelectCertificateA, 4
IMPORT CryptUIDlgSelectCertificateFromStore, 28
IMPORT CryptUIDlgSelectCertificateW, 4
IMPORT CryptUIDlgSelectStoreA, 4
IMPORT CryptUIDlgSelectStoreW, 4
IMPORT CryptUIDlgViewCRLA, 4
IMPORT CryptUIDlgViewCRLW, 4
IMPORT CryptUIDlgViewCTLA, 4
IMPORT CryptUIDlgViewCTLW, 4
IMPORT CryptUIDlgViewCertificateA, 8
IMPORT CryptUIDlgViewCertificatePropertiesA, 8
IMPORT CryptUIDlgViewCertificatePropertiesW, 8
IMPORT CryptUIDlgViewCertificateW, 8
IMPORT CryptUIDlgViewContext, 24
IMPORT CryptUIDlgViewSignerInfoA, 4
IMPORT CryptUIDlgViewSignerInfoW, 4
IMPORT CryptUIFreeCertificatePropertiesPagesA, 8
IMPORT CryptUIFreeCertificatePropertiesPagesW, 8
IMPORT CryptUIFreeViewSignaturesPagesA, 8
IMPORT CryptUIFreeViewSignaturesPagesW, 8
IMPORT CryptUIGetCertificatePropertiesPagesA, 16
IMPORT CryptUIGetCertificatePropertiesPagesW, 16
IMPORT CryptUIGetViewSignaturesPagesA, 12
IMPORT CryptUIGetViewSignaturesPagesW, 12
IMPORT CryptUIStartCertMgr, 16
IMPORT CryptUIWizBuildCTL, 24
IMPORT CryptUIWizCertRequest, 24
IMPORT CryptUIWizCreateCertRequestNoDS, 16
IMPORT CryptUIWizDigitalSign, 20
IMPORT CryptUIWizExport, 20
IMPORT CryptUIWizFreeCertRequestNoDS, 4
IMPORT CryptUIWizFreeDigitalSignContext, 4
IMPORT CryptUIWizImport, 20
IMPORT CryptUIWizQueryCertRequestNoDS, 8
IMPORT CryptUIWizSubmitCertRequestNoDS, 24
IMPORT EnrollmentCOMObjectFactory_getInstance, 20
IMPORT I_CryptUIProtect, 24
IMPORT I_CryptUIProtectFailure, 12
IMPORT LocalEnroll, 92
IMPORT LocalEnrollNoDS, 92
IMPORT RetrievePKCS7FromCA, 28
IMPORT WizardFree, 4

%endif