%ifndef __d3drm_INC__
%define __d3drm_INC__

IMPORT D3DRMColorGetAlpha
IMPORT D3DRMColorGetBlue
IMPORT D3DRMColorGetGreen
IMPORT D3DRMColorGetRed
IMPORT D3DRMCreateColorRGBA
IMPORT D3DRMMatrixFromQuaternion
IMPORT D3DRMQuaternionFromRotation
IMPORT D3DRMQuaternionMultiply
IMPORT D3DRMQuaternionSlerp
IMPORT D3DRMVectorAdd
IMPORT D3DRMVectorCrossProduct
IMPORT D3DRMVectorDotProduct
IMPORT D3DRMVectorModulus
IMPORT D3DRMVectorNormalize
IMPORT D3DRMVectorRandom
IMPORT D3DRMVectorReflect
IMPORT D3DRMVectorRotate
IMPORT D3DRMVectorScale
IMPORT D3DRMVectorSubtract
IMPORT Direct3DRMCreate, 4

%endif