%ifndef __ddraw_INC__
%define __ddraw_INC__

IMPORT DDGetAttachedSurfaceLcl, 12
IMPORT DDInternalLock, 8
IMPORT DDInternalUnlock, 4
IMPORT DSoundHelp, 12
IMPORT DirectDrawCreate, 12
IMPORT DirectDrawCreateClipper, 12
IMPORT DirectDrawCreateEx, 16
IMPORT DirectDrawEnumerateA, 8
IMPORT DirectDrawEnumerateExA, 12
IMPORT DirectDrawEnumerateExW, 12
IMPORT DirectDrawEnumerateW, 8
IMPORT GetDDSurfaceLocal, 12
IMPORT GetSurfaceFromDC, 12

%endif