%ifndef __glu32_INC__
%define __glu32_INC__

IMPORT gluBeginCurve, 4
IMPORT gluBeginPolygon, 4
IMPORT gluBeginSurface, 4
IMPORT gluBeginTrim, 4
IMPORT gluBuild1DMipmaps, 24
IMPORT gluBuild2DMipmaps, 28
IMPORT gluCylinder, 36
IMPORT gluDeleteNurbsRenderer, 4
IMPORT gluDeleteQuadric, 4
IMPORT gluDeleteTess, 4
IMPORT gluDisk, 28
IMPORT gluEndCurve, 4
IMPORT gluEndPolygon, 4
IMPORT gluEndSurface, 4
IMPORT gluEndTrim, 4
IMPORT gluErrorString, 4
IMPORT gluErrorUnicodeStringEXT, 4
IMPORT gluGetNurbsProperty, 12
IMPORT gluGetString, 4
IMPORT gluGetTessProperty, 12
IMPORT gluLoadSamplingMatrices, 16
IMPORT gluLookAt, 72
IMPORT gluNewNurbsRenderer, 0
IMPORT gluNewQuadric, 0
IMPORT gluNewTess, 0
IMPORT gluNextContour, 8
IMPORT gluNurbsCallback, 12
IMPORT gluNurbsCurve, 28
IMPORT gluNurbsProperty, 12
IMPORT gluNurbsSurface, 44
IMPORT gluOrtho2D, 32
IMPORT gluPartialDisk, 44
IMPORT gluPerspective, 32
IMPORT gluPickMatrix, 36
IMPORT gluProject, 48
IMPORT gluPwlCurve, 20
IMPORT gluQuadricCallback, 12
IMPORT gluQuadricDrawStyle, 8
IMPORT gluQuadricNormals, 8
IMPORT gluQuadricOrientation, 8
IMPORT gluQuadricTexture, 8
IMPORT gluScaleImage, 36
IMPORT gluSphere, 20
IMPORT gluTessBeginContour, 4
IMPORT gluTessBeginPolygon, 8
IMPORT gluTessCallback, 12
IMPORT gluTessEndContour, 4
IMPORT gluTessEndPolygon, 4
IMPORT gluTessNormal, 28
IMPORT gluTessProperty, 16
IMPORT gluTessVertex, 12
IMPORT gluUnProject, 48

%endif