%ifndef __uxtheme_INC__
%define __uxtheme_INC__

IMPORT CloseThemeData, 4
IMPORT DrawThemeBackground, 24
IMPORT DrawThemeBackgroundEx, 24
IMPORT DrawThemeEdge, 32
IMPORT DrawThemeIcon, 28
IMPORT DrawThemeParentBackground, 12
IMPORT DrawThemeText, 36
IMPORT EnableThemeDialogTexture, 8
IMPORT EnableTheming, 4
IMPORT GetCurrentThemeName, 24
IMPORT GetThemeAppProperties, 0
IMPORT GetThemeBackgroundContentRect, 24
IMPORT GetThemeBackgroundExtent, 24
IMPORT GetThemeBackgroundRegion, 24
IMPORT GetThemeBool, 20
IMPORT GetThemeColor, 20
IMPORT GetThemeDocumentationProperty, 16
IMPORT GetThemeEnumValue, 20
IMPORT GetThemeFilename, 24
IMPORT GetThemeFont, 24
IMPORT GetThemeInt, 20
IMPORT GetThemeIntList, 20
IMPORT GetThemeMargins, 28
IMPORT GetThemeMetric, 24
IMPORT GetThemePartSize, 28
IMPORT GetThemePosition, 20
IMPORT GetThemePropertyOrigin, 20
IMPORT GetThemeRect, 20
IMPORT GetThemeString, 24
IMPORT GetThemeSysBool, 8
IMPORT GetThemeSysColor, 8
IMPORT GetThemeSysColorBrush, 8
IMPORT GetThemeSysFont, 12
IMPORT GetThemeSysInt, 12
IMPORT GetThemeSysSize, 8
IMPORT GetThemeSysString, 16
IMPORT GetThemeTextExtent, 36
IMPORT GetThemeTextMetrics, 20
IMPORT GetWindowTheme, 4
IMPORT HitTestThemeBackground, 40
IMPORT IsAppThemed, 0
IMPORT IsThemeActive, 0
IMPORT IsThemeBackgroundPartiallyTransparent, 12
IMPORT IsThemeDialogTextureEnabled, 4
IMPORT IsThemePartDefined, 12
IMPORT OpenThemeData, 8
IMPORT SetThemeAppProperties, 4
IMPORT SetWindowTheme, 12
IMPORT ThemeInitApiHook, 8

%endif