%ifndef __odbccp32_INC__
%define __odbccp32_INC__

IMPORT SQLConfigDataSource, 16
IMPORT SQLConfigDataSourceW, 16
IMPORT SQLConfigDriver, 28
IMPORT SQLConfigDriverW, 28
IMPORT SQLCreateDataSource, 8
IMPORT SQLCreateDataSourceW, 8
IMPORT SQLGetAvailableDrivers, 16
IMPORT SQLGetAvailableDriversW, 16
IMPORT SQLGetConfigMode, 4
IMPORT SQLGetInstalledDrivers, 12
IMPORT SQLGetInstalledDriversW, 12
IMPORT SQLGetPrivateProfileString, 24
IMPORT SQLGetPrivateProfileStringW, 24
IMPORT SQLGetTranslator, 32
IMPORT SQLGetTranslatorW, 32
IMPORT SQLInstallDriver, 20
IMPORT SQLInstallDriverEx, 28
IMPORT SQLInstallDriverExW, 28
IMPORT SQLInstallDriverManager, 12
IMPORT SQLInstallDriverManagerW, 12
IMPORT SQLInstallDriverW, 20
IMPORT SQLInstallODBC, 16
IMPORT SQLInstallODBCW, 16
IMPORT SQLInstallTranslator, 32
IMPORT SQLInstallTranslatorEx, 28
IMPORT SQLInstallTranslatorExW, 28
IMPORT SQLInstallTranslatorW, 32
IMPORT SQLInstallerError, 20
IMPORT SQLInstallerErrorW, 20
IMPORT SQLManageDataSources, 4
IMPORT SQLPostInstallerError, 8
IMPORT SQLPostInstallerErrorW, 8
IMPORT SQLReadFileDSN, 24
IMPORT SQLReadFileDSNW, 24
IMPORT SQLRemoveDSNFromIni, 4
IMPORT SQLRemoveDSNFromIniW, 4
IMPORT SQLRemoveDefaultDataSource, 0
IMPORT SQLRemoveDriver, 12
IMPORT SQLRemoveDriverManager, 4
IMPORT SQLRemoveDriverW, 12
IMPORT SQLRemoveTranslator, 8
IMPORT SQLRemoveTranslatorW, 8
IMPORT SQLSetConfigMode, 4
IMPORT SQLValidDSN, 4
IMPORT SQLValidDSNW, 4
IMPORT SQLWriteDSNToIni, 8
IMPORT SQLWriteDSNToIniW, 8
IMPORT SQLWriteFileDSN, 16
IMPORT SQLWriteFileDSNW, 16
IMPORT SQLWritePrivateProfileString, 16
IMPORT SQLWritePrivateProfileStringW, 16

%endif