%ifndef __credui_INC__
%define __credui_INC__

IMPORT CredUICmdLinePromptForCredentialsA, 36
IMPORT CredUICmdLinePromptForCredentialsW, 36
IMPORT CredUIConfirmCredentialsA, 8
IMPORT CredUIConfirmCredentialsW, 8
IMPORT CredUIParseUserNameA, 20
IMPORT CredUIParseUserNameW, 20
IMPORT CredUIPromptForCredentialsA, 40
IMPORT CredUIPromptForCredentialsW, 40
IMPORT CredUIReadSSOCredW, 8
IMPORT CredUIStoreSSOCredW, 16

%endif