%ifndef __dsound_INC__
%define __dsound_INC__

IMPORT DirectSoundCaptureCreate8, 12
IMPORT DirectSoundCaptureCreate, 12
IMPORT DirectSoundCaptureEnumerateA, 8
IMPORT DirectSoundCaptureEnumerateW, 8
IMPORT DirectSoundCreate8, 12
IMPORT DirectSoundCreate, 12
IMPORT DirectSoundEnumerateA, 8
IMPORT DirectSoundEnumerateW, 8
IMPORT DirectSoundFullDuplexCreate, 40
IMPORT GetDeviceID, 8

%endif