%ifndef __dsuiext_INC__
%define __dsuiext_INC__

IMPORT CheckDsPolicy, 8
IMPORT DsBrowseForContainerA, 4
IMPORT DsBrowseForContainerW, 4
IMPORT DsGetFriendlyClassName, 12
IMPORT DsGetIcon, 16
IMPORT FormatDirectoryName, 12
IMPORT FormatMsgBox
IMPORT FormatMsgResource
IMPORT GetArrayContents, 12
IMPORT GetDisplayNameFromADsPath, 20
IMPORT GetStringElementA, 16
IMPORT GetStringElementW, 16
IMPORT LocalAllocStringA2W, 8
IMPORT LocalAllocStringA, 8
IMPORT LocalAllocStringLenA, 8
IMPORT LocalAllocStringLenW, 8
IMPORT LocalAllocStringW2A, 8
IMPORT LocalAllocStringW, 8
IMPORT LocalFreeStringA, 4
IMPORT LocalFreeStringW, 4
IMPORT LocalQueryStringA, 12
IMPORT LocalQueryStringW, 12
IMPORT ObjectClassFromSearchColumn, 8
IMPORT PutStringElementA, 12
IMPORT PutStringElementW, 12
IMPORT ShowDirectoryUI, 0
IMPORT StringDPA_AppendStringA, 12
IMPORT StringDPA_AppendStringW, 12
IMPORT StringDPA_DeleteString, 8
IMPORT StringDPA_Destroy, 4
IMPORT StringDPA_InsertStringA, 12
IMPORT StringDPA_InsertStringW, 12
IMPORT StringFromSearchColumn, 8

%endif