%ifndef __mspatchc_INC__
%define __mspatchc_INC__

IMPORT CreatePatchFileA, 20
IMPORT CreatePatchFileByHandles, 20
IMPORT CreatePatchFileByHandlesEx, 32
IMPORT CreatePatchFileExA, 32
IMPORT CreatePatchFileExW, 32
IMPORT CreatePatchFileW, 20
IMPORT ExtractPatchHeaderToFileA, 8
IMPORT ExtractPatchHeaderToFileByHandles, 8
IMPORT ExtractPatchHeaderToFileW, 8
IMPORT GetFilePatchSignatureA, 36
IMPORT GetFilePatchSignatureByHandle, 36
IMPORT GetFilePatchSignatureW, 36

%endif