%ifndef __mspatcha_INC__
%define __mspatcha_INC__

IMPORT ApplyPatchToFileA, 16
IMPORT ApplyPatchToFileByHandles, 16
IMPORT ApplyPatchToFileByHandlesEx, 24
IMPORT ApplyPatchToFileExA, 24
IMPORT ApplyPatchToFileExW, 24
IMPORT ApplyPatchToFileW, 16
IMPORT GetFilePatchSignatureA, 36
IMPORT GetFilePatchSignatureByHandle, 36
IMPORT GetFilePatchSignatureW, 36
IMPORT TestApplyPatchToFileA, 12
IMPORT TestApplyPatchToFileByHandles, 12
IMPORT TestApplyPatchToFileW, 12

%endif