%ifndef __rtutils_INC__
%define __rtutils_INC__

IMPORT LogErrorA, 16
IMPORT LogErrorW, 16
IMPORT LogEventA, 16
IMPORT LogEventW, 16
IMPORT MprSetupProtocolEnum, 12
IMPORT MprSetupProtocolFree, 4
IMPORT QueueWorkItem, 12
IMPORT RouterAssert, 16
IMPORT RouterGetErrorStringA, 8
IMPORT RouterGetErrorStringW, 8
IMPORT RouterLogDeregisterA, 4
IMPORT RouterLogDeregisterW, 4
IMPORT RouterLogEventA, 24
IMPORT RouterLogEventDataA, 28
IMPORT RouterLogEventDataW, 28
IMPORT RouterLogEventExA
IMPORT RouterLogEventExW
IMPORT RouterLogEventStringA, 28
IMPORT RouterLogEventStringW, 28
IMPORT RouterLogEventValistExA, 24
IMPORT RouterLogEventValistExW, 24
IMPORT RouterLogEventW, 24
IMPORT RouterLogRegisterA, 4
IMPORT RouterLogRegisterW, 4
IMPORT SetIoCompletionProc, 8
IMPORT TraceDeregisterA, 4
IMPORT TraceDeregisterExA, 8
IMPORT TraceDeregisterExW, 8
IMPORT TraceDeregisterW, 4
IMPORT TraceDumpExA, 28
IMPORT TraceDumpExW, 28
IMPORT TraceGetConsoleA, 8
IMPORT TraceGetConsoleW, 8
IMPORT TracePrintfA
IMPORT TracePrintfExA
IMPORT TracePrintfExW
IMPORT TracePrintfW
IMPORT TracePutsExA, 12
IMPORT TracePutsExW, 12
IMPORT TraceRegisterExA, 8
IMPORT TraceRegisterExW, 8
IMPORT TraceVprintfExA, 16
IMPORT TraceVprintfExW, 16

%endif