%ifndef __traffic_INC__
%define __traffic_INC__

IMPORT TcAddFilter, 12
IMPORT TcAddFlow, 20
IMPORT TcCloseInterface, 4
IMPORT TcDeleteFilter, 4
IMPORT TcDeleteFlow, 4
IMPORT TcDeregisterClient, 4
IMPORT TcEnumerateFlows, 20
IMPORT TcEnumerateInterfaces, 12
IMPORT TcGetFlowNameA, 12
IMPORT TcGetFlowNameW, 12
IMPORT TcModifyFlow, 8
IMPORT TcOpenInterfaceA, 16
IMPORT TcOpenInterfaceW, 16
IMPORT TcQueryFlowA, 16
IMPORT TcQueryFlowW, 16
IMPORT TcQueryInterface, 20
IMPORT TcRegisterClient, 16
IMPORT TcSetFlowA, 16
IMPORT TcSetFlowW, 16
IMPORT TcSetInterface, 16

%endif