%ifndef __usp10_INC__
%define __usp10_INC__

IMPORT ScriptApplyDigitSubstitution, 12
IMPORT ScriptApplyLogicalWidth, 36
IMPORT ScriptBreak, 16
IMPORT ScriptCPtoX, 36
IMPORT ScriptCacheGetHeight, 12
IMPORT ScriptFreeCache, 4
IMPORT ScriptGetCMap, 24
IMPORT ScriptGetFontProperties, 12
IMPORT ScriptGetGlyphABCWidth, 16
IMPORT ScriptGetLogicalWidths, 28
IMPORT ScriptGetProperties, 8
IMPORT ScriptIsComplex, 12
IMPORT ScriptItemize, 28
IMPORT ScriptJustify, 24
IMPORT ScriptLayout, 16
IMPORT ScriptPlace, 36
IMPORT ScriptRecordDigitSubstitution, 8
IMPORT ScriptShape, 40
IMPORT ScriptStringAnalyse, 52
IMPORT ScriptStringCPtoX, 16
IMPORT ScriptStringFree, 4
IMPORT ScriptStringGetLogicalWidths, 8
IMPORT ScriptStringGetOrder, 8
IMPORT ScriptStringOut, 32
IMPORT ScriptStringValidate, 4
IMPORT ScriptStringXtoCP, 16
IMPORT ScriptString_pLogAttr, 4
IMPORT ScriptString_pSize, 4
IMPORT ScriptString_pcOutChars, 4
IMPORT ScriptTextOut, 56
IMPORT ScriptXtoCP, 36

%endif