%ifndef __webpost_INC__
%define __webpost_INC__

IMPORT WpBindToSiteA, 24
IMPORT WpBindToSiteW, 24
IMPORT WpCreateSiteA, 20
IMPORT WpCreateSiteW, 20
IMPORT WpDeleteSiteA, 4
IMPORT WpDeleteSiteW, 4
IMPORT WpDoesSiteExistA, 8
IMPORT WpDoesSiteExistW, 8
IMPORT WpEnumProvidersA, 12
IMPORT WpEnumProvidersW, 12
IMPORT WpGetErrorStringA, 12
IMPORT WpGetErrorStringW, 12
IMPORT WpListSitesA, 12
IMPORT WpListSitesW, 12
IMPORT WpPostA, 32
IMPORT WpPostW, 32

%endif